apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /products
        backend:
          serviceName: rvstore-product-api
          servicePort: 9001
      - path: /orders
        backend:
          serviceName: rvstore-order-api
          servicePort: 9002
